package com.quu.model;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

//This class is used with createBillboardsAndDependants.

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@JsonIgnoreProperties(ignoreUnknown = true)
//The DPS fields are generated by us.
public class BBCampaignIn {
	
	private int id;  //If null is passed it will have its default value of 0  
	private String name;
    private String advertiser;
    private String message_type;
    private String start_date;
    private String end_date; 
    private String remarks; 
    
    private String rt1;
    private String rt2;
    private String dps1;
    private String dps2;
    private String dps3;
    private String dps4;
    private String dps5;
    private String dps6;
    private String dps7;
    private String dps8;
    private String imageUrl;
    //The image name is not passed from controller. It is a constant that will be saved only if image param comes with a value from controller.
  	private String imageName;  	
  	//This is not an attribute of the BBCampaign post. It is set outside but we use that value inside every campaign.
  	private int activate;
        
    @JsonProperty("schedules")	
	private List<BBScheduleIn> scheduleList;
}
